# This file was generated by pkgs.mastodon.updateScript.
{ fetchFromGitHub, applyPatches }: let
  src = fetchFromGitHub {
    owner = "glitch-soc";
    repo = "mastodon";
    rev = "main";
    hash = "sha256-uA0Yrn3t228c1equsm1GkH/w+rFqyPVUJ8giNsgYTcQ=";
  };
in applyPatches {
  inherit src;
  patches = [];
}
